YUD-36 - Successfully enroll course + resolve conflict
DeadlineShooters/Yudemy-Mobile pull request #21
Opened 2024-03-14 20:22 UTC by liwjln

2024-03-17 09:29 UTC, ThanhVan8 requested changes

2024-03-17 09:29 UTC, ThanhVan8 commented on build.gradle
> +    id 'org.jetbrains.kotlin.android' version '1.8.10' apply false
version ở main là 1.8.20

2024-03-17 09:29 UTC, ThanhVan8 commented on app/src/main/AndroidManifest.xml
chưa khai báo FilterActivity (mở filter ở SearchFragment bị báo lỗi)

2024-03-17 09:29 UTC, ThanhVan8 commented on app/src/main/res/layout/fragment_wishlist.xml
recycler view của wishlist thiếu constraint bottom nên bị bottom navigation che mất

2024-03-18 02:51 UTC, liwjln commented on app/src/main/res/layout/fragment_wishlist.xml
wishlist là fragment nên bị bottom nav che a bà

2024-03-18 06:07 UTC, ThanhVan8 commented on app/src/main/res/layout/fragment_wishlist.xml
à ý tui là cái ListView 'wishlist__list' á (tui nhìn lộn thành RecyclerView), ông thêm constraint bottom cho nó dính phía dưới với để layout_height là match constraint là hong bị che

2024-03-18 06:17 UTC, ThanhVan8 requested changes

2024-03-18 06:17 UTC, ThanhVan8 commented on .vscode/settings.json
ignore file này nha

2024-03-18 15:14 UTC, ThanhVan8 approved these changes

2024-03-18 15:35 UTC, merged