YUD135 - Add favorites, update UI for free course, and recount stats after enrollment
DeadlineShooters/Yudemy-Mobile pull request #65
Opened 2024-04-28 07:31 UTC by liwjln

2024-05-03 02:56 UTC, ItsMeNozo requested changes
- onResume của wishlist ông chưa fetch lại các khóa được wishlist nên khi remove a course from wishlist rồi quay trả về màn hình wishlist -> vẫn còn khóa đó
- Bấm nút quay về ở màn hình search ko được 
- lúc chưa search gì hết mà Filter Free/Paid xong quay về màn hình search chả show gì hết
- lúc bấm vô từ discover course rồi vô course detail cần thể hiện progress dialog loading nếu ko người dùng

2024-05-03 02:56 UTC, ItsMeNozo commented on app/src/main/java/com/deadlineshooters/yudemy/models/Course.kt
> +    var totalRevenue: Double = 0.0,
Này là Int chứ ko phải Double

2024-05-04 03:57 UTC, ItsMeNozo commented
@liwjln ông bỏ nút back ở fragment search luôn đi :) Do ko thấy udemy có để. Mà bấm nút quay lại thì nó quay lại được nhưng mấy icon ở bottom navigator bị sai 
![image](https://github.com/DeadlineShooters/Yudemy-Mobile/assets/91927045/9193baff-5ca2-4329-8213-08704f03dd67)

2024-05-04 04:16 UTC, ItsMeNozo commented
1. mà sao có cái dòng dưới course name là id gì vậy 
![image](https://github.com/DeadlineShooters/Yudemy-Mobile/assets/91927045/492a31f2-7c0e-4b6b-b9b1-9afe0240644b)

2. sao thanh toán bằng google pay ko được?
![image](https://github.com/DeadlineShooters/Yudemy-Mobile/assets/91927045/33b9d54f-458f-4f21-85bb-a3d4cf9332e9)

2024-05-04 07:08 UTC, ItsMeNozo requested changes

2024-05-04 07:08 UTC, ItsMeNozo commented on app/src/main/java/com/deadlineshooters/yudemy/activities/CourseDetailActivity.kt
> -        userRepository.isInCourseList(course.id) { isInCourseList ->
sao xóa mất nguyên chỗ này rồi. Bữa tui add này vì nếu khóa đó của chính người dùng luôn thì thể hiện "Go to course" luôn chứ ko có cho buy hay enroll gì hết. 
Ví dụ khóa này của chính tui tạo, mà thay gì button enroll now thì là "Go to course" 
![image](https://github.com/DeadlineShooters/Yudemy-Mobile/assets/91927045/6a41a7e3-de64-47ba-b8f9-fd14276b9846)

2024-05-04 07:08 UTC, ItsMeNozo commented on app/src/main/java/com/deadlineshooters/yudemy/activities/CourseDetailActivity.kt
> -    private fun updateButtonVisibility(isBuyVisible: Int, isCourseVisible: Int) {
sao xóa luôn updateButtonVisiblity rồi

2024-05-04 07:22 UTC, liwjln commented on app/src/main/java/com/deadlineshooters/yudemy/activities/CourseDetailActivity.kt
> -    private fun updateButtonVisibility(isBuyVisible: Int, isCourseVisible: Int) {
tui thêm lại r nha, chắc do auto merge hoặc tui vô tình xóa mất

2024-05-04 07:23 UTC, ItsMeNozo commented on app/src/main/java/com/deadlineshooters/yudemy/activities/CourseDetailActivity.kt
> -    private fun updateButtonVisibility(isBuyVisible: Int, isCourseVisible: Int) {
ok

2024-05-04 07:28 UTC, ItsMeNozo commented on app/src/main/java/com/deadlineshooters/yudemy/activities/CourseDetailActivity.kt
> -    private fun updateButtonVisibility(isBuyVisible: Int, isCourseVisible: Int) {
nó bị merge sai rồi :) 
![image](https://github.com/DeadlineShooters/Yudemy-Mobile/assets/91927045/116ee690-b2dd-4894-a8e1-3f11b364942d)

tài khoản: 
dungtuyetngoc@gmail.com
123456

ông test trên đó do tui có tạo khóa sẵn

2024-05-04 07:59 UTC, liwjln commented on app/src/main/java/com/deadlineshooters/yudemy/activities/CourseDetailActivity.kt
> -    private fun updateButtonVisibility(isBuyVisible: Int, isCourseVisible: Int) {
tui thêm mấy dòng để check giá r nha

2024-05-04 08:07 UTC, ItsMeNozo approved these changes

2024-05-04 08:07 UTC, merged